services:
  ws-backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws

    ports:
      - 8080:8080
    
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    environment:
      NEXT_PUBLIC_FE_URL: "http://localhost:3000/canvas/"            
      NEXT_PUBLIC_WS_URL: "ws://localhost:8080"
    ports:
      - 3000:3000
    depends_on:
      - ws-backend

    