FROM node:20-alpine

RUN npm install -g pnpm 

WORKDIR /excalidraw/fe

COPY ./packages ./packages
COPY ./apps/frontend ./apps/frontend

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

RUN pnpm install 

EXPOSE 3000

CMD ["pnpm","run" , "start:frontend"]